export const emailSafeFonts = [
    { name: 'Arial', value: 'Arial, Helvetica, sans-serif' },
    { name: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
    { name: 'Tahoma', value: 'Tahoma, Geneva, sans-serif' },
    { name: 'Trebuchet MS', value: "'Trebuchet MS', Helvetica, sans-serif" },
    { name: 'Times New Roman', value: "'Times New Roman', Times, serif" },
    { name: 'Georgia', value: 'Georgia, serif' },
    { name: 'Courier New', value: "'Courier New', Courier, monospace" }
];

// Expanded Contact DB with Link handling logic built-in
export const contactIconsDB = {
    'phone': { name: 'Telephone', icon: 'phone', prefix: 'tel:', isLink: true },
    'email': { name: 'Email', icon: 'new-post', prefix: 'mailto:', isLink: true },
    'address': { name: 'Address', icon: 'marker', prefix: '', isLink: false },
    'fax': { name: 'Fax', icon: 'fax', prefix: 'tel:', isLink: true },
    'domain': { name: 'Website', icon: 'domain', prefix: '', isLink: true },
    'skype': { name: 'Skype', icon: 'skype', prefix: 'skype:', isLink: true },
    'whatsapp': { name: 'WhatsApp', icon: 'whatsapp', prefix: 'https://wa.me/', isLink: true },
    'ctaButton': { name: 'Button Link', icon: 'link', prefix: '', isLink: true },
};

export const socialsDB = [
    // --- Top Social & Messaging ---
    { id: 'facebook', name: 'Facebook', color: '#1877F2', icon: 'facebook-new' },
    { id: 'instagram', name: 'Instagram', color: '#E4405F', icon: 'instagram-new' },
    { id: 'linkedin', name: 'LinkedIn', color: '#0A66C2', icon: 'linkedin' },
    { id: 'twitter', name: 'Twitter', color: '#1DA1F2', icon: 'twitter' },
    { id: 'youtube', name: 'YouTube', color: '#FF0000', icon: 'youtube-play' },
    { id: 'whatsapp', name: 'WhatsApp', color: '#25D366', icon: 'whatsapp' },
    { id: 'telegram', name: 'Telegram', color: '#24A1DE', icon: 'telegram-app' },
    { id: 'tiktok', name: 'TikTok', color: '#000000', icon: 'tiktok' },
    { id: 'snapchat', name: 'Snapchat', color: '#FFFC00', icon: 'snapchat' },
    { id: 'pinterest', name: 'Pinterest', color: '#E60023', icon: 'pinterest' },
    { id: 'discord', name: 'Discord', color: '#5865F2', icon: 'discord-logo' },
    { id: 'reddit', name: 'Reddit', color: '#FF4500', icon: 'reddit' },
    { id: 'tumblr', name: 'Tumblr', color: '#35465C', icon: 'tumblr' },
    { id: 'messenger', name: 'Messenger', color: '#00B2FF', icon: 'facebook-messenger' },
    { id: 'skype', name: 'Skype', color: '#00AFF0', icon: 'skype' },
    { id: 'wechat', name: 'WeChat', color: '#7BB32E', icon: 'chat' },
    { id: 'line', name: 'LINE', color: '#00C300', icon: 'line-me' },
    { id: 'viber', name: 'Viber', color: '#665CAC', icon: 'viber' },
    { id: 'vk', name: 'VKontakte', color: '#4A76A8', icon: 'vk-com' },
    { id: 'kakaotalk', name: 'KakaoTalk', color: '#FFCD00', icon: 'speech-bubble' },

    // --- Content, Media & Streaming ---
    { id: 'medium', name: 'Medium', color: '#000000', icon: 'medium-monogram' },
    { id: 'twitch', name: 'Twitch', color: '#9146FF', icon: 'twitch' },
    { id: 'spotify', name: 'Spotify', color: '#1DB954', icon: 'spotify' },
    { id: 'soundcloud', name: 'SoundCloud', color: '#FF3300', icon: 'soundcloud' },
    { id: 'vimeo', name: 'Vimeo', color: '#1AB7EA', icon: 'vimeo' },
    { id: 'netflix', name: 'Netflix', color: '#E50914', icon: 'netflix' },
    { id: 'imdb', name: 'IMDb', color: '#F5C518', icon: 'imdb' },
    { id: 'blogger', name: 'Blogger', color: '#FF5722', icon: 'blogger' },
    { id: 'wordpress', name: 'WordPress', color: '#21759B', icon: 'wordpress' },
    { id: 'quora', name: 'Quora', color: '#B92B27', icon: 'quora' },
    { id: 'goodreads', name: 'Goodreads', color: '#382110', icon: 'goodreads' },
    // { id: 'mixcloud', name: 'Mixcloud', color: '#5000FF', icon: 'mixcloud' }, // Fixed
    { id: 'tidal', name: 'Tidal', color: '#000000', icon: 'tidal' },
    { id: 'flipboard', name: 'Flipboard', color: '#E12828', icon: 'flipboard' },
    { id: 'pocket', name: 'Pocket', color: '#EE4056', icon: 'pocket' },
    { id: 'rss', name: 'RSS', color: '#F26522', icon: 'rss' },
    { id: 'wikipedia', name: 'Wikipedia', color: '#000000', icon: 'wikipedia' },
    { id: 'askfm', name: 'Ask.fm', color: '#D32A2F', icon: 'ask-question' },
    { id: 'substack', name: 'Substack', color: '#FF6719', icon: 'bookmark' },
    { id: 'ghost', name: 'Ghost', color: '#000000', icon: 'ghost' },

    // --- Work, Tech & Design ---
    { id: 'slack', name: 'Slack', color: '#4A154B', icon: 'slack-new' },
    { id: 'github', name: 'GitHub', color: '#181717', icon: 'github' },
    { id: 'gitlab', name: 'GitLab', color: '#FCA326', icon: 'gitlab' },
    { id: 'stackoverflow', name: 'Stack Overflow', color: '#F58025', icon: 'code' },
    { id: 'behance', name: 'Behance', color: '#1769FF', icon: 'behance' },
    { id: 'dribbble', name: 'Dribbble', color: '#EA4C89', icon: 'dribbble' },
    { id: 'deviantart', name: 'DeviantArt', color: '#05CC47', icon: 'paint-palette' },
    { id: 'envato', name: 'Envato', color: '#81B441', icon: 'envato' },
    { id: 'fiverr', name: 'Fiverr', color: '#1DBF73', icon: 'fiverr' },
    { id: 'upwork', name: 'Upwork', color: '#14A800', icon: 'upwork' },
    { id: 'trello', name: 'Trello', color: '#0079BF', icon: 'trello' },
    { id: 'basecamp', name: 'Basecamp', color: '#5ECC62', icon: 'tent' },
    { id: 'asana', name: 'Asana', color: '#273347', icon: 'asana' },
    { id: 'jira', name: 'Jira', color: '#0052CC', icon: 'project' },
    { id: 'confluence', name: 'Confluence', color: '#172B4D', icon: 'document' },
    { id: 'zoom', name: 'Zoom', color: '#2D8CFF', icon: 'zoom' },
    { id: 'dropbox', name: 'Dropbox', color: '#0061FF', icon: 'dropbox' },
    { id: 'google-drive', name: 'Google Drive', color: '#FFD020', icon: 'google-drive' },
    { id: 'figma', name: 'Figma', color: '#F24E1E', icon: 'figma' },
    { id: 'sketch', name: 'Sketch', color: '#F7B500', icon: 'sketch' },

    // --- Marketplaces & Services ---
    { id: 'amazon', name: 'Amazon', color: '#FF9900', icon: 'amazon' },
    { id: 'ebay', name: 'eBay', color: '#E53238', icon: 'ebay' },
    { id: 'etsy', name: 'Etsy', color: '#F16521', icon: 'etsy' },
    { id: 'alibaba', name: 'Alibaba', color: '#FF6A00', icon: 'shopping-bag' },
    { id: 'shopify', name: 'Shopify', color: '#95BF47', icon: 'shopify' },
    { id: 'airbnb', name: 'Airbnb', color: '#FF5A5F', icon: 'airbnb' },
    { id: 'booking', name: 'Booking.com', color: '#003580', icon: 'bed' },
    { id: 'tripadvisor', name: 'Tripadvisor', color: '#34E0A1', icon: 'tripadvisor' },
    { id: 'yelp', name: 'Yelp', color: '#D32323', icon: 'star' },
    { id: 'foursquare', name: 'Foursquare', color: '#F94877', icon: 'marker' },
    { id: 'zillow', name: 'Zillow', color: '#006AFF', icon: 'home' },
    { id: 'houzz', name: 'Houzz', color: '#4DBC15', icon: 'houzz' },
    { id: 'meetup', name: 'Meetup', color: '#F24059', icon: 'meetup' },
    { id: 'eventbrite', name: 'Eventbrite', color: '#F05537', icon: 'ticket' },
    // { id: 'tinder', name: 'Tinder', color: '#FE3C72', icon: 'tinder' }, // Fixed
    { id: 'patreon', name: 'Patreon', color: '#FF424D', icon: 'patreon' },
    { id: 'kickstarter', name: 'Kickstarter', color: '#2BDE73', icon: 'rocket' },
    { id: 'indiegogo', name: 'Indiegogo', color: '#EB1478', icon: 'banknotes' },
    { id: 'gofundme', name: 'GoFundMe', color: '#00B964', icon: 'donate' },
    // { id: 'squarespace', name: 'Squarespace', color: '#000000', icon: 'squarespace' }, // Fixed

    // --- Dev Tools, OS & Platforms ---
    { id: 'apple', name: 'Apple', color: '#000000', icon: 'mac-os' },
    { id: 'android', name: 'Android', color: '#3DDC84', icon: 'android-os' },
    { id: 'windows', name: 'Windows', color: '#0078D6', icon: 'windows-client' },
    { id: 'ubuntu', name: 'Ubuntu', color: '#E95420', icon: 'ubuntu' },
    { id: 'linux', name: 'Linux', color: '#FCC624', icon: 'linux' },
    { id: 'chrome', name: 'Chrome', color: '#4285F4', icon: 'chrome' },
    { id: 'firefox', name: 'Firefox', color: '#FF7139', icon: 'firefox' },
    { id: 'safari', name: 'Safari', color: '#000000', icon: 'safari' },
    // { id: 'edge', name: 'Edge', color: '#0078D7', icon: 'microsoft-edge' }, // Fixed
    { id: 'internet-explorer', name: 'Explorer', color: '#00BCE4', icon: 'internet-explorer' },
    { id: 'app-store', name: 'App Store', color: '#0D96F6', icon: 'apple-app-store' },
    { id: 'google-play', name: 'Google Play', color: '#000000', icon: 'google-play' },
    { id: 'aws', name: 'AWS', color: '#232F3E', icon: 'cloud' },
    { id: 'google-cloud', name: 'GCP', color: '#4285F4', icon: 'cloud' },
    { id: 'azure', name: 'Azure', color: '#0089D6', icon: 'cloud' },
    { id: 'digitalocean', name: 'DigitalOcean', color: '#0080FF', icon: 'water' },
    { id: 'heroku', name: 'Heroku', color: '#430098', icon: 'server' },
    { id: 'vercel', name: 'Vercel', color: '#000000', icon: 'sort-up' },
    { id: 'netlify', name: 'Netlify', color: '#00C7B7', icon: 'globe' },
    { id: 'docker', name: 'Docker', color: '#2496ED', icon: 'docker' },

    // --- Programming Languages & Frameworks ---
    { id: 'javascript', name: 'JavaScript', color: '#F7DF1E', icon: 'javascript' },
    { id: 'python', name: 'Python', color: '#3776AB', icon: 'python' },
    { id: 'html5', name: 'HTML5', color: '#E34F26', icon: 'html-5' },
    { id: 'css3', name: 'CSS3', color: '#1572B6', icon: 'css3' },
    { id: 'sass', name: 'Sass', color: '#CC6699', icon: 'sass' },
    { id: 'react', name: 'React', color: '#61DAFB', icon: 'react-native' },
    { id: 'vue', name: 'Vue.js', color: '#4FC08D', icon: 'leaf' },
    { id: 'angular', name: 'Angular', color: '#DD0031', icon: 'angularjs' },
    // { id: 'nodejs', name: 'Node.js', color: '#339933', icon: 'nodejs' }, // Fixed
    { id: 'git', name: 'Git', color: '#F05032', icon: 'git' },

    // --- Crypto & Finance ---
    { id: 'paypal', name: 'PayPal', color: '#00457C', icon: 'paypal' },
    { id: 'stripe', name: 'Stripe', color: '#008CDD', icon: 'stripe' },
    { id: 'square', name: 'Square', color: '#3D454E', icon: 'square' },
    { id: 'visa', name: 'Visa', color: '#1434CB', icon: 'visa' },
    { id: 'mastercard', name: 'Mastercard', color: '#EB001B', icon: 'mastercard' },
    { id: 'apple-pay', name: 'Apple Pay', color: '#000000', icon: 'apple-pay' },
    { id: 'google-pay', name: 'Google Pay', color: '#4285F4', icon: 'google-logo' },
    { id: 'bitcoin', name: 'Bitcoin', color: '#F7931A', icon: 'bitcoin' },
    { id: 'ethereum', name: 'Ethereum', color: '#3C3C3D', icon: 'ethereum' },
    { id: 'litecoin', name: 'Litecoin', color: '#345D9D', icon: 'litecoin' },
    { id: 'dogecoin', name: 'Dogecoin', color: '#C2A633', icon: 'dogecoin' },
    { id: 'binance', name: 'Binance', color: '#F3BA2F', icon: 'currency-exchange' },
    { id: 'coinbase', name: 'Coinbase', color: '#0052FF', icon: 'wallet' },
    { id: 'kraken', name: 'Kraken', color: '#5741D9', icon: 'octopus' },
    { id: 'robinhood', name: 'Robinhood', color: '#00C805', icon: 'feather' },

    // --- Misc, Niche, and Legacy ---
    { id: 'threads', name: 'Threads', color: '#000000', icon: 'threads' },
    { id: 'x', name: 'X', color: '#000000', icon: 'x' },
    { id: 'mastodon', name: 'Mastodon', color: '#6364FF', icon: 'elephant' },
    { id: 'weibo', name: 'Weibo', color: '#E6162D', icon: 'weibo' },
    // { id: 'baidu', name: 'Baidu', color: '#2932E1', icon: 'baidu' }, // Fixed
    // { id: 'naver', name: 'Naver', color: '#03C75A', icon: 'naver' }, // Fixed
    { id: 'odnoklassniki', name: 'Odnoklassniki', color: '#ED812B', icon: 'odnoklassniki' },
    { id: 'xing', name: 'XING', color: '#026466', icon: 'xing' },
    { id: 'digg', name: 'Digg', color: '#000000', icon: 'digg' },
    { id: 'myspace', name: 'Myspace', color: '#030303', icon: 'myspace' },
    { id: 'google-plus', name: 'Google+', color: '#DB4437', icon: 'google-plus' },
    { id: 'ello', name: 'Ello', color: '#000000', icon: 'smiling' },
    { id: '500px', name: '500px', color: '#0099E5', icon: '500px' },
    { id: 'flickr', name: 'Flickr', color: '#0063DC', icon: 'flickr' },
    { id: 'unsplash', name: 'Unsplash', color: '#000000', icon: 'unsplash' },
    { id: 'slideshare', name: 'SlideShare', color: '#0077B5', icon: 'presentation' },
    { id: 'drupal', name: 'Drupal', color: '#0678BE', icon: 'drupal' },
    { id: 'bitbucket', name: 'Bitbucket', color: '#0052CC', icon: 'bitbucket' },
    { id: 'angellist', name: 'AngelList', color: '#000000', icon: 'peace-pigeon' },
    { id: 'hacker-news', name: 'Hacker News', color: '#FF6600', icon: 'news' },
    { id: 'crunchbase', name: 'Crunchbase', color: '#0288D1', icon: 'database' },
    { id: 'product-hunt', name: 'Product Hunt', color: '#DA552F', icon: 'product' },
    { id: 'y-combinator', name: 'Y Combinator', color: '#F0652F', icon: 'y-combinator' },
    { id: 'glassdoor', name: 'Glassdoor', color: '#0CAA41', icon: 'door' },
    // { id: 'trustpilot', name: 'Trustpilot', color: '#00B67A', icon: 'trustpilot' }, // Fixed
    { id: 'capterra', name: 'Capterra', color: '#000000', icon: 'search' },
    { id: 'adobe-photoshop', name: 'Photoshop', color: '#31A8FF', icon: 'adobe-photoshop' },
    { id: 'adobe-illustrator', name: 'Illustrator', color: '#FF9A00', icon: 'adobe-illustrator' },
    { id: 'adobe-xd', name: 'Adobe XD', color: '#FF61F6', icon: 'adobe-xd' },
    // { id: 'invision', name: 'InVision', color: '#FF3366', icon: 'invision' }, // Fixed
    { id: 'strava', name: 'Strava', color: '#FC4C02', icon: 'strava' },
    { id: 'nintendo', name: 'Nintendo', color: '#E60012', icon: 'nintendo' },
    // { id: 'playstation', name: 'PlayStation', color: '#003791', icon: 'playstation' }, // Fixed
    { id: 'steam', name: 'Steam', color: '#000000', icon: 'steam' },
    { id: 'yahoo', name: 'Yahoo', color: '#410093', icon: 'yahoo' },
    // { id: 'mailchimp', name: 'Mailchimp', color: '#FFE01B', icon: 'mailchimp' }, // Fixed
    { id: 'target', name: 'Target', color: '#CC0000', icon: 'target' }
];